### PR TITLE
fix(5.0): Collection of fixes, mostly due to upgrading DD version

### LINKED ISSUE #48: LocalStack extension dashboard UI is broken
## Describe the bug
LocalStack extension dashboard top menu UI is broken inside Docker desktop application. 

## Steps to Reproduce
1. Go to Extension once you launch Docker desktop 
2. Click on LocalStack extension 
you will see UI is broken 

## Expected behavior
Button and top menu should display clearly. 

## Screenshots
Screenshot 2023-11-15 at 1 59 55 PM

## Additional context
Using MacBook Pro ( macOS ventura )

### PR DESCRIPTION
**Pull request by Pive01**
This PR adds the following fixes:
- Fixes app bar, with the new version of DD it renders a default height of 41px , changed to `auto`
- Fixes status page showing as list instead of grid: not sure why but the style in the class is not picked up as first in order of importance so adding `display: grid` in the `style` parameter renders it correctly
- Added  auth token support and using it as default authentication method
- Fixed problem of Start button not working if you have an image with no tag (so built it yourself)
- Removed EXTRA_CORS_ALLOWRD_ORIGINS as default env var when starting LS from the extension

## Images

image

Screenshot from 2023-11-15 11-17-49

Closes #48

### CODE REVIEW

File: ui/src/components/Views/Configs/SettingsForm.tsx [hunk 1]
```diff
@@ -175,8 +175,8 @@ export const SettingsForm = ({ initialState }: MountPointFormProps): ReactElemen
           {
             activeStep === 1 &&
             <Typography>
-              In order to start the Pro container, add a configuration with the variable LOCALSTACK_API_KEY 
-              set to your API key and select that configuration in the top right corner
+              In order to start the Pro container, add a configuration with the variable LOCALSTACK_AUTH_TOKEN 
+              set to your auth token and select that configuration in the top right corner
```
Comment (lukqw) [inline ui/src/components/Views/Configs/SettingsForm.tsx:179]: we are still supporting auth tokens, so this should probably mentioned API Keys as well, i.e.

`API Keys are also supported, but will be deprecated in the future`

**Review by lukqw — APPROVED** [review]
