### PR TITLE
Full support on Windows

### LINKED ISSUE #22: Bug: Extension does not start up with error "locating users: using /tmp as mount point"
On Windows 11, I am receiving the following error:
``` Error while locating users: using /tmp as mount point ```

Feel free to ask if you need more details or are able to provide how to get a more detailed log of the error.

### LINKED ISSUE #28: Possible small improvements
Small things that I noticed while using the extensions:

1. During the update, it mentions an image was updated. It's really hard to see which one. Can it be more distinguished?
image

2. Can we provide a list of the images that will be updated? Put them in bold for easier reading, and change the color of the text from gray to white? It's not very readable.
image

3. Make the values in Variable field always in uppercase.
Why is there no option to edit (modify) previously assigned variables and their values? I think this was previously possible.
image20

4. Can this be hidden? 
image

5. The State is not updated from Stopped to Running. 
image

### LINKED ISSUE #29: [bug] Localstack docker image started but not visible in docker
Using this version:  `pive01/localstack-docker-extension:0.3.2`

Used config:
LOCALSTACK_API_KEY=XXX, DEBUG=1, LOCALSTACK_VOLUME_DIR=/C/temp/localstack

When hitting the start button, I received all the INFO, DEBUG messages as toast notifications:
image
image

I can see that the docker image is started:
image

Running `localstack status` to get info if localstack is started:

```
localstack status                                                                                                                            

┌─────────────────┬───────────────────────────────────────────────────────┐
│ Runtime version │ 1.4.1.dev                                             │
│ Docker image    │ tag: latest, id: 48775529339f, 📆 2023-02-23T12:47:41 │
│ Runtime status  │ ✖ stopped                                             │
└─────────────────┴───────────────────────────────────────────────────────┘
```

Testing out if it works anyway.
```
awslocal docdb create-db-cluster --db-cluster-identifier fb231 --engine docdb  
{
    "DBCluster": {
        "DBClusterIdentifier": "fb231",
        "DBClusterParameterGroup": "default.docdb",
        "Status": "available",
        "Endpoint": "localhost:38397",
        "MultiAZ": false,
        "Engine": "docdb",
        "Port": 38397,
        "MasterUsername": "test",
        "DBClusterMembers": [],
        "StorageEncrypted": false,
        "DBClusterArn": "arn:aws:rds:us-east-1:000000000000:cluster:fb231"
    }
}
```

If I check Docker Desktop Containers page if the container is running it's not mentioned there. Only the docdb image is visible.

image

Logs:
```

LocalStack version: 1.4.1.dev
LocalStack Docker container id: 1a1f007cd964
LocalStack build date: 2023-02-23
LocalStack build git hash: 4be57540

Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Ready.

2023-02-24T12:33:29.996  INFO --- [  MainThread] l.extensions.platform      : loaded 0 extensions
2023-02-24T12:33:30.003  INFO --- [  MainThread] botocore.credentials       : Found credentials in environment variables.
2023-02-24T12:33:30.042  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-02-24T12:33:30.042  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-02-24T12:33:30.049  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-02-24T12:33:30.049  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-02-24T12:33:30.070  WARN --- [-functhread6] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-02-24T12:33:30.070  WARN --- [-functhread6] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-02-24T12:33:30.070  INFO --- [-functhread6] hypercorn.error            : Running on https://0.0.0.0:443 (CTRL + C to quit)
2023-02-24T12:33:30.070  INFO --- [-functhread6] hypercorn.error            : Running on https://0.0.0.0:443 (CTRL + C to quit)
2023-02-24T12:35:27.076  INFO --- [   asgi_gw_0] botocore.credentials       : Found credentials in environment variables.
2023-02-24T12:35:27.278  INFO --- [functhread27] l.services.docdb.docdb_api : Starting Document DB instance on port 38397
2023-02-24T12:35:29.718  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS rds.CreateDBCluster => 200
```

### PR DESCRIPTION
**Pull request by Pive01**
## Content 

- Added full support on Windows (no more error locating user)
- Added switch on Windows for selecting in which distro should we mount the container 
- Switched to invoke binaries instead of mounting container for checking folder content (much faster)
- Restyled mount point selection form
- Implemented suggestion on #28 
- Updated Dockerfile

## Images

<h3> Unix <h3/>

Screenshot from 2023-02-23 13-28-32

<h3> Windows <h3/>

Screenshot 2023-02-23 133721

Closes #22
Closes #28 
Closes #29

### CODE REVIEW

File: ui/src/App.tsx [hunk 1]
```diff
@@ -13,9 +13,11 @@ const useStyles = makeStyles(() => createStyles({
 
 export const App = (): ReactElement => {
   const [selected, setSelected] = useState<number>(0);
-  const { data: mountPoint } = useMountPoint();
+  const { user, os } = useMountPoint();
   const classes = useStyles();
-  const shouldDialogOpen = !mountPoint || mountPoint === '';
+  const  ddClient  = useDDClient();
```
Comment (whummer) [inline ui/src/App.tsx:18]:
```suggestion
  const ddClient = useDDClient();
```

Curious to find out why the linter would not report this (minor) formatting issue? If I run `(cd ui; npm run lint)`, the result seems to be clean. Could this be related to the custom `rules` in `.eslintrc.js`?

File: ui/src/components/Header/Controller.tsx [hunk 2]
```diff
@@ -14,13 +14,15 @@ import { DockerContainer, DockerImage } from '../../types';
 import { DownloadProgressDialog } from '../Feedback/DownloadProgressDialog';
 import { ProgressButton } from '../Feedback';
 
+const EXCLUDED_ERROR_TOAST = ['Successfully activated API key','Execution of "prepare_host"','DEBUG'];
```
Comment (whummer) [inline ui/src/components/Header/Controller.tsx:17]:
```suggestion
const EXCLUDED_ERROR_TOAST = ['Successfully activated API key', 'Execution of "prepare_host"', 'DEBUG'];
```

Again, would be great if the linter could catch this.. 👍

File: ui/src/components/Header/Controller.tsx [hunk 3]
```diff
@@ -38,22 +40,27 @@ export const Controller = (): ReactElement => {
   }, [isLoading]);
 
   const buildMountArg = () => {
-    const OSPath = ddClient.host.platform === 'darwin'
-      ? 'Users'
-      : 'home';
+    if(user === '../temp'){
```
Comment (whummer) [inline ui/src/components/Header/Controller.tsx:43]: Can we add some comments in here to explain why/how this case can happen? Seems a bit counter-intuitive that the `user` variable can contain a relative path name..

File: ui/src/components/Header/Controller.tsx [hunk 4]
```diff
@@ -84,10 +91,7 @@ export const Controller = (): ReactElement => {
     ddClient.docker.cli.exec('run', args, {
       stream: {
         onOutput(data): void {
-          if (data.stderr
-            && !data.stderr.includes('Successfully') // Api key activation is included in the error stream
-            && !data.stderr.includes('Execution of "prepare_host"')) {
-
+          if (!EXCLUDED_ERROR_TOAST.some(item => data.stderr.includes(item))) {
```
Comment (whummer) [inline ui/src/components/Header/Controller.tsx:94]: nit: seems a bit easier to read if we assign the result of the function to a local variable (may be more of a personal taste, though). Something like:
```suggestion
          const isExcludedLog = EXCLUDED_ERROR_TOAST.some(item => data.stderr.includes(item));
          if (!isExcludedLog) {
```

File: ui/src/components/Views/Configs/MountPointForm.tsx [hunk 5]
```diff
@@ -1,137 +1,187 @@
...
-import { DownloadProgress } from '../../Feedback';
+import {
+  getOSsFromBinary,
+  getUsersFromBinaryUnix,
+  getUsersFromBinaryWindows,
+  useDDClient,
+  useMountPoint,
+} from '../../../services';
+
+const ShrinkedCircularProgress = (): ReactElement =>  <CircularProgress size={20} sx={{ margin: 1}}/>;
```
Comment (whummer) [inline ui/src/components/Views/Configs/MountPointForm.tsx:24]: nit: indentation matters! ;)  
```suggestion
const ShrinkedCircularProgress = (): ReactElement => <CircularProgress size={20} sx={{ margin: 1 }}/>;
```

File: ui/src/components/Views/Configs/MountPointForm.tsx [hunk 6]
```diff
@@ -1,137 +1,187 @@
...
-    const res = await ddClient.docker.cli.exec('run',
-      ['--rm', '--entrypoint=', '-v', `/${path}:/users`, 'localstack/localstack', 'ls', '/users']);
-
-    if (res.stderr !== '' || res.stdout === '') {
-      ddClient.desktopUI.toast.error(`Error while locating users: ${res.stderr}\n using /tmp as mount point`);
-      setUserState({ loading: false, selectedUser: 'tmp', users: ['tmp'] });
-      setMountPointUser('tmp');
+  const getMountPointPath = (): string => {
+    if(ddClient.host.platform === 'darwin'){
+      return `/Users/${userState.selectedUser || 'loading...'}/Library/Caches/localstack/volume`;
```
Comment (whummer) [inline ui/src/components/Views/Configs/MountPointForm.tsx:37]: We should make sure to only use this string (including the string `loading...`) for display purposes, and not as an actual mount point. (haven't fully checked whether that's the case)

File: ui/src/components/Views/Configs/MountPointForm.tsx [hunk 7]
```diff
@@ -1,137 +1,187 @@
...
-        if (isPresent) {
-          checkHomeDir();
-        } else {
-          setIsPullingImage(true);
-        }
+  useEffect(() => {
+    const execChecks = async () => {
+      if (userState.users.length === 0
+        || (ddClient.host.platform === 'win32' && osState.OSs.length === 0)) {
+        locateMountPoint();
```
Comment (whummer) [inline ui/src/components/Views/Configs/MountPointForm.tsx:87]: nit: not sure what the convention is here, but presumably we're missing an indentation here?
```suggestion
          locateMountPoint();
```

Again, should ideally be caught/defined by the linter

File: ui/src/components/Views/Configs/MountPointForm.tsx [hunk 8]
```diff
@@ -1,137 +1,187 @@
...
+
+  useEffect(() => {
+    if (osState.selectedOS) {
+      checkUser();
+    }
+  }, [triggerUserCheck]);
 
   const onClose = () => {
-    setMountPointUser(userState.selectedUser);
+    setMountPointData(`${userState.selectedUser},${osState.selectedOS}`);
```
Comment (whummer) [inline ui/src/components/Views/Configs/MountPointForm.tsx:101]: Wondering if there could be a more elegant way to pass the user and OS. Rather than a comma-separated string which we're later splitting, could we just use an array/tuple?

File: ui/src/components/Views/Configs/MountPointForm.tsx [hunk 9]
```diff
@@ -1,137 +1,187 @@
...
-              </>
-            }
-            {
-              (hasLocalImage.checking || userState.loading) && <CircularProgress />
-            }
+              {
+                osState.loading ?
+                  <ShrinkedCircularProgress/> 
+                  :
+                  <FormControl sx={{ minWidth: 120 }} size="small" variant='outlined'>
```
Comment (whummer) [inline ui/src/components/Views/Configs/MountPointForm.tsx:130]: nit: looks like we're using a mix of single and double quotes in JSX elements - could be an opportunity to unify the styles? (again, a linter could take care of that..)

File: ui/src/components/Views/Update/UpdateDialog.tsx [hunk 10]
```diff
@@ -51,16 +56,29 @@ export const UpdateDialog = ({ open, onClose }: Props): ReactElement => {
...
+                <br />
+              </>
+            ))
+          }
+          {
+            logs.length === 0 &&
             <>
               <Typography>
-                {`${log}`}
+                Updating docker images
```
Comment (whummer) [inline ui/src/components/Views/Update/UpdateDialog.tsx:73]:
```suggestion
                Updating Docker images
```

**Review by whummer — COMMENTED** [review]
Nice set of changes @Pive01 , excited to get the enhanced support for Windows released soon! 🚀 

Added an initial set of review comments - mostly some minor suggestions. I'm sure @lukqw will have more in-depth feedback for the next iteration. 👍

File: ui/src/components/Views/Configs/MountPointForm.tsx (hunk 7 above)
Comment (Pive01) [reply ui/src/components/Views/Configs/MountPointForm.tsx:87]: This is technically not an error since the body is 1 indent more than the if...maybe 
```
if ( x 
|| y ) {
  locateMountPoint();
```
  would be better?

File: ui/src/components/Views/Update/UpdateDialog.tsx [hunk 11]
```diff
@@ -23,10 +23,15 @@ export const UpdateDialog = ({ open, onClose }: Props): ReactElement => {
...
         onOutput(data): void {
-          setLogs((current) => [...current, data.stdout
+          const resultStr = data.stdout
             .replaceAll('â', '')
             .replaceAll('â', '✅')
-            .replaceAll('â', '❌')]);
+            .replaceAll('â', '❌');
+
+          if (resultStr.endsWith('updated')) {
+            resultStr.concat(' 🔼');
```
[the remark this answers is not in the document]
Comment (Pive01) [reply ui/src/components/Views/Update/UpdateDialog.tsx:32]: You're right, I missed that

File: ui/src/components/Views/Configs/MountPointForm.tsx (hunk 6 above)
Comment (Pive01) [reply ui/src/components/Views/Configs/MountPointForm.tsx:37]: this is only for display :smile:

File: ui/src/components/Header/Controller.tsx [hunk 12]
```diff
@@ -38,22 +41,27 @@ export const Controller = (): ReactElement => {
   }, [isLoading]);
 
   const buildMountArg = () => {
-    const OSPath = ddClient.host.platform === 'darwin'
-      ? 'Users'
-      : 'home';
+    if (user === ERROR_USER) {
```
Comment (lukqw) [inline ui/src/components/Header/Controller.tsx:44]: It seems like we're using a string here to encode that a user is not found. 
Isn't there a better way of facilitating this? We could also use '' to signify no user being found and for us to use the default volume dir

**Review by lukqw — COMMENTED** [review]
nice work 👍 couple of nits and picks to get this one over the line 🚀

File: ui/src/components/Views/Update/UpdateDialog.tsx [hunk 13]
```diff
@@ -23,10 +23,15 @@ export const UpdateDialog = ({ open, onClose }: Props): ReactElement => {
     const listener = ddClient.docker.cli.exec('run', UPDATE_ARGS, {
       stream: {
         onOutput(data): void {
-          setLogs((current) => [...current, data.stdout
+          let resultStr = data.stdout
             .replaceAll('â', '')
             .replaceAll('â', '✅')
-            .replaceAll('â', '❌')]);
+            .replaceAll('â', '❌');
```
[the remark this answers is not in the document]
Comment (Pive01) [reply ui/src/components/Views/Update/UpdateDialog.tsx:29]: It's not the same, it's just displayed like this probably because is not UTF-8 encode :+1:

File: ui/src/components/Views/Update/UpdateDialog.tsx [hunk 14]
```diff
@@ -51,16 +56,29 @@ export const UpdateDialog = ({ open, onClose }: Props): ReactElement => {
...
+              <>
+                <Typography>
+                  {log}
+                </Typography>
+                <br />
+              </>
+            ))
+          }
+          {
+            logs.length === 0 &&
```
[the remark this answers is not in the document]
Comment (Pive01) [reply ui/src/components/Views/Update/UpdateDialog.tsx:70]: Once you launch the `localstack update` command from the cli "Updating docker images" is the first string you get but it takes some seconds to display it, if I checked this when `isUpdating` we would have it duplicated since I', not filtering the output of the command

File: ui/src/components/Views/Update/UpdateDialog.tsx (hunk 10 above)
Comment (Pive01) [reply ui/src/components/Views/Update/UpdateDialog.tsx]: @whummer you should change it also here https://github.com/localstack/localstack/blob/master/localstack/cli/localstack.py#L373

**Review by HarshCasper — APPROVED** [review]

**Review by whummer — APPROVED** [review]
Thanks for addressing all the comments. Great job! 🚀 

LGTM, but will let @lukqw do the final sign-off 👍

**Review by lukqw — APPROVED** [review]
Lets get this bread 🍞 🚀 
Nice work! @Pive01 🙌
